<?php

namespace App\Actions\Media;

use App\Enums\MediaCollection;
use App\Exceptions\GalleryFull;
use App\Models\Business;
use App\Models\User;
use App\Support\Audit\AuditLogger;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 * Stores an already validated image in one of the business collections (docs/17).
 *
 * The file gets a random name (docs/16), a default alt text and goes to the private
 * originals disk; the public WebP conversions are generated by the queue. Single-file
 * collections (logo, cover) replace the previous image. Audited when the actor is not the owner.
 */
class AddBusinessImage
{
    public function __construct(private AuditLogger $audit) {}

    /**
     * @param  UploadedFile|string  $file  an uploaded file or an absolute path to one
     *
     * @throws GalleryFull
     */
    public function handle(Business $business, User $actor, MediaCollection $collection, UploadedFile|string $file, ?string $alt = null): Media
    {
        $max = (int) config('avytra.media.gallery_max');

        if ($collection === MediaCollection::Gallery && $business->getMedia($collection->value)->count() >= $max) {
            throw new GalleryFull($business, $max);
        }

        $extension = $file instanceof UploadedFile ? $file->extension() : pathinfo($file, PATHINFO_EXTENSION);
        $path = $file instanceof UploadedFile ? $file->getRealPath() : $file;

        $media = $business->addMedia($path)
            ->usingName($business->name)
            ->usingFileName(Str::random(40).'.'.strtolower($extension))
            ->withCustomProperties(['alt' => filled($alt) ? trim((string) $alt) : $this->defaultAlt($business, $collection)])
            ->toMediaCollection($collection->value);

        $business->unsetRelation('media');

        if ($actor->isNot($business->owner)) {
            $this->audit->log(
                action: 'business.images_updated_by_admin',
                subject: $business,
                actor: $actor,
                onBehalfOf: $business->owner,
                changes: ['after' => ['operation' => 'added', 'collection' => $collection->value, 'media_id' => $media->getKey()]],
            );
        }

        return $media;
    }

    private function defaultAlt(Business $business, MediaCollection $collection): string
    {
        return match ($collection) {
            MediaCollection::Logo => __(':name, logo', ['name' => $business->name]),
            MediaCollection::Cover => __(':name, cover image', ['name' => $business->name]),
            MediaCollection::Gallery => __(':name, image :number', [
                'name' => $business->name,
                'number' => $business->getMedia($collection->value)->count() + 1,
            ]),
        };
    }
}
